### ISSUE TITLE
Returned results limit

### ISSUE THREAD

**Issue by bvego** [gooddata/gooddata-react-components#1083]
Hi there. I'm trying to sort my bar chart by a measure and only display the first 5 results - but I couldn't find something like a `limit` or `take` prop. Am I missing something or?

Thanks!

**Comment by bvego** [comment]
Hi,

is there any update/answer regarding this? 😅

**Comment by ivan-nejezchleb** [comment]
Hi, you are right. Something like "limit" or "top" is not supported yet, but we will prepare for some of the next versions. For now, you need to do such slicing on client by client code
