### ISSUE TITLE
Change chart height/width

### ISSUE THREAD

**Issue by bvego** [gooddata/gooddata-react-components#1123]
Hi there. I can't find how to change the chart height on the docs link:
https://sdk.gooddata.com/gooddata-ui/docs/chart_config.html

Is there any way to do it right now?

**Comment by ivan-nejezchleb** [comment]
Hi, size of chart is defined by its parent container. Example can be seen here
https://gooddata-examples.herokuapp.com/advanced/responsive.
Hope this will help. Our documentation and live examples are valuable source of information.
Next time for generic questions use please https://stackoverflow.com/ and label your question by 'gooddata' tag. Github issues should be reserved for real bugs in our product. Thank you
