### ISSUE TITLE
Missing sdk from Components' prop types

### ISSUE THREAD

**Issue by zbycz** [gooddata/gooddata-react-components#623]
Hi my friends,

I am currently working at @kiwicom on a quick SBA prototype. When using typescript I encountered this issue with bucket components - the `sdk` prop is missing both from TS and documentation. I use `@gooddata/react-components@5.3.2`, but the same issue is unfortunately also in `next-6.0.0`.

btw, its only matter of typing - without typescript, the `sdk` prop get passed down all right.

```js
import { AreaChart } from '@gooddata/react-components';
<AreaChart projectId={projectId} measures={...} viewBy={...} sdk={sdk} />
// TS2339: Property 'sdk' does not exist on type 'IntrinsicAttributes & IAreaChartProps'.
```

**Possible solution:** Afm components publicize the `sdk` prop through `IDataSourceProviderProps`, so the issue stands directly at bucket component level. I think `sdk?: SDK` could be added alongside `projectId` to each component, which is trivial :)

btw2, the sdk prop seems to be missing also from documentation of [afmComponents](https://sdk.gooddata.com/gooddata-ui/docs/next/afm_components.html) and [AttributeFilter](https://sdk.gooddata.com/gooddata-ui/docs/next/attribute_filter_component.html). Both works ok without TS.

**Comment by macekond** [comment]
Hi @zbycz,

thank you for the bug report. We were able to fix it and it is going to be delivered in the next SDK version (6.0).

**Comment by zbycz** [comment]
Thanks @macekond. Loving it! :-)
