### ISSUE TITLE
requires Node <= 9

### ISSUE THREAD

**Issue by lazaruslarue** [gooddata/gooddata-react-components#802]
any way we could get 10 in there? it's an LTS :+1:

**Comment by ivan-nejezchleb** [comment]
Hi. [Documentation](https://sdk.gooddata.com/gooddata-ui/docs/ht_create_your_first_visualization.html#step-1-get-create-react-app) mentions "NOTE: The supported versions of Node are ^8.10.0 or >=9.10.0. Using a different version may result in errors." Have you tried version 10 which is >=9.10.0?

**Comment by ivan-nejezchleb** [comment]
no feedback from reporter -> closing
