### ISSUE TITLE
DualAxisLineChart has awkward y-axis indicators

### ISSUE THREAD

**Issue by lazaruslarue** [gooddata/gooddata-react-components#808]
Originating library: https://github.com/uber/react-vis

It's awkward: 

![image](https://user-images.githubusercontent.com/1894215/53600785-07845600-3b70-11e9-8f68-b0031943cee9.png)

**Comment by ivan-nejezchleb** [comment]
Please provide some minimal reproducer of your issue. 
If you combine Gooddata.UI <Execute> component and then pass execution result into your own visualization based on react-vis lib, you probably need to somehow transform data to match chart library requirements or you found a bug in charting library

**Comment by ivan-nejezchleb** [comment]
no feedback from reporter -> closing
